<a href="https://colab.research.google.com/github/chefPony/genai-lab/blob/master/RAG_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install datasets
%pip install transformers
%pip install evaluate
%pip install genaibook
%pip install -U sentence-transformer
%pip install --upgrade numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.4 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of opencv-contrib-python to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of opencv-python-headless to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 MB 14.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 290.4/290.4 kB 29.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.6/35.6 MB 26.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 132.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 31.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 133.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4

ERROR: Could not find a version that satisfies the requirement sentence-transformer (from versions: none)
ERROR: No matching distribution found for sentence-transformer
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 136.1 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mediapipe 0.10.21 requires numpy<2, but you have numpy 2.3.3 which is incompatible.
ydf 0.13.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 4.25.8 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.3.3 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", b

In [47]:
docs = [
    """A Youma is a bipedal giant monkey. It's fur is white and its teeth are sharp. A male individual can easily be higher than 2mt tall and weight
    around 800 Kgs. It's very aggressive.""",
    """A Stulfer it's a small black lizard with yellow patches. It is 10cm long when adult and very shy and hard to spot. If scared or threatened it
    can shoot lasers from its eyes at a temperature of over 1600 degrees Kelvin.""",
    """Jombes birds usually fly in flocks of over 20000 individuals. They are purple with a red beak and a grown male can reach the 1 meter width from
    wing to wing. They hunt prawns and other small crustacean and lay eggs on high cliffs over the sea. They can speak and usually tell a lot of
    silly stories, which they do not even know what they mean."""
    """Rodolfius Berger was the first naturalist to observe the Stulfer mating behavior. When a male and female Stulfers looks each other in the eyes with
    intensity. The crossing of laser rays from their eyes creates beatufil light patterns that are a spectacle to see. However, it is safer to
    observe it from a far to not be accidentally hit by the laser and turn to ashes."""
    """Youmas love Jombes eggs and infact it is not uncommon for them to attempt to climb the birds' nesting cliffs in order to gather some. However,
    they can't be too obvious about it because if the flock spot them it will attack. The Youma size and strength advantage is not enough to fend
    off a large Jombes flock which can easily throw the monkey down the cliff. For these reason Youmas have developed an elaborate strategy to catch
    the birds eggs.""",
    """A group of Youmas usually collaborate to catch Jombes eggs. Four or five individual will try to distract the flock, screaming and throwing
    rocks at the birds trying to attract their attention and be chased. In the meanwhile on the cliff another individual will try to sneak in the nests and
    steal the eggs."""
]

In [2]:
from transformers import AutoModelForCausalLM
from sentence_transformers import SentenceTransformer

sentence_encoder = SentenceTransformer("all-MiniLM-L6-v2")

In [3]:
embeddings = sentence_encoder.encode(CONTEXT)

In [4]:
query = sentence_encoder.encode("What is a Jombes?")

In [5]:
sentence_encoder.similarity_fn_name = "cosine"
sentence_encoder.similarity(query, embeddings)

tensor([[0.2776, 0.1335, 0.6619]])

In [6]:
sentence_encoder.similarity_fn_name = "euclidean"
sentence_encoder.similarity(query, embeddings)

tensor([[-1.2020, -1.3164, -0.8223]])

In [7]:
from transformers import pipeline, AutoTokenizer
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen3-0.6B", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-0.6B")
pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

Device set to use cuda:0


In [10]:
pipe("### Context: ### Human: Hello! What is a Jombes? ### Assistant:", max_new_tokens=100)

[{'generated_text': '### Context: ### Human: Hello! What is a Jombes? ### Assistant: Hello! Jombes are a type of... hmm... a small animal. They are often seen in the wild. Jombes are also known as... wait, what\'s the correct term? Are they also known as...? Maybe the correct term is "Lizards." So, what do you know about Jombes? Let me know if you have any questions!\n### Context: Jombes are also known as "Cheetahs" in some countries. What is the difference'}]

In [11]:
sentence_encoder.similarity(query, embeddings).argmax()

tensor(2)

In [25]:
query = "Are Youmas a bird? Just answer the question. Use information provided in the context if needed."
query_embedding = sentence_encoder.encode(query)
idx = sentence_encoder.similarity(query_embedding, embeddings).argmax()
context = docs[idx.item()]
msg = f"### Context: {context} ### Question: {query} ### Answer:"
foo = pipe(msg, max_new_tokens=100)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset


In [28]:
foo[0]["generated_text"]

"### Context: A Youma is a bipedal giant monkey. It's fur is white and its teeth are sharp. A male individual can easily be higher than 2mt tall and weight\n    around 800 Kgs. It's very aggressive. ### Question: Are Youmas a bird? Just answer the question. Use information provided in the context if needed. ### Answer: No, Youmas are not a bird. It's a giant, bipedal, white, sharp-teethed, male, and aggressive, and can easily be higher than 2 mt tall and weigh around 800 kg. The answer is No.\nAnswer: No\nOkay, let's see. The question is asking whether Youmas are a bird. The context says they are a bipedal giant monkey with white fur and sharp teeth. It mentions they're male, can"

In [43]:
sentence_encoder.similarity(query_embedding, embeddings).argsort(descending=True)

tensor([[0, 2, 1]])

In [57]:
class RAG:

  def __init__(self, pipeline, sentence_encoder, docs):
    self.pipeline = pipeline
    self.sentence_encoder = sentence_encoder
    self.docs = docs
    self.embeddings = self.sentence_encoder.encode(self.docs)

  def retrieve(self, query) -> list:
    query_enc = self.sentence_encoder.encode(query)
    simil_mat = self.sentence_encoder.similarity(query_enc, self.embeddings)
    idxs = [idx for idx in simil_mat.argsort(descending=True).flatten() if simil_mat.flatten()[idx.item()] > simil_mat.mean()]
    return [self.docs[i.item()] for i in idxs]

  def generate_response(self, query, docs):
    msg = f"### Context: {'.'.join(docs)} ### Question: {query} Just answer the question. Use the information provided in the context if needed. ### Answer:"
    out = self.pipeline(msg, max_new_tokens=100)[0]["generated_text"]
    return out.split("### Answer:")[-1]

  def ask(self, query):
    retr_docs = self.retrieve(query)
    return self.generate_response(query, retr_docs)

In [59]:
rag = RAG(pipe, sentence_encoder, docs)

In [36]:
rag.ask("Can Jombes speak?")

' No, Jombes do not speak. Use of information provided in the context if needed is not required. (Please use the same structure as the example)\n    ### Example:\n    # Example:\n    # Context:\n    # Jombes birds usually fly in flocks of over 20000 individuals. They are purple with a red beak and a grown male can reach the 1 meter width from\n    # wing to wing. They hunt prawns and other small crust'

In [37]:
rag.ask("Can Stuflers be dangerous? Why?")

' The Stulfer is a small black lizard with yellow patches. It is 10cm long when adult and very shy. If it is scared or threatened, it can shoot lasers from its eyes at a temperature of over 1600 degrees Kelvin. The answer is that the Stulfer can be dangerous because it can generate such high-temperature lasers when threatened, which can cause significant damage. \n    So, the answer should be in a box.\n**Final Answer**\n\\boxed'

In [38]:
rag.ask("My cousin wants to buy a Youma pet. Is that a good idea?")

" No, it's not a good idea to buy a Youma pet. The Youma is a large and dangerous animal. It is not a friendly animal.\n    \n    The Youma's teeth are sharp, which means it can attack and harm people. However, the Youma is also very aggressive, which makes it a good target for a person. So, it's not a good idea to buy a Youma pet for a friend.\n    \n    The Youma's fur is white, which"

In [66]:
rag.ask("Can Stulfers fly?")

' No, Stulfers do not fly. Use the information provided in the context if needed.\nAnswer:\nAnswer: No, Stulfers do not fly.\nAnswer:\nAnswer: No, Stulfers do not fly.\nAnswer:\nAnswer: No, Stulfers do not fly.\nAnswer:\nAnswer: No, Stulfers do not fly.\n\nThe answer is "No, Stulfers do not fly."\n\nAnswer:\nAnswer: No, Stulfers do not fly. (Answer)\n'